name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install backend deps
        run: |
          cd backend-node
          npm install
      - name: Run backend tests
        run: |
          cd backend-node
          npm test -- --runInBand
      - name: Install frontend deps
        run: |
          cd app
          npm install
      - name: Build frontend
        run: |
          cd app
          npm run build
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}-backend:latest"
          docker build -t "$IMAGE" backend-node
          docker push "$IMAGE"
      - name: Build frontend image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}-frontend:latest"
          docker build -t "$IMAGE" app
          docker push "$IMAGE"
